name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
#  release-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 15
#
#      - name: Publish
#        run: ./gradlew packageDistributionForCurrentOS
#      # Upload to Drive
#      - name: Upload deb to Google Drive
#        uses: anwarpro/upload-to-drive@master
#        with:
#          target: desktop/build/compose/binaries/main/deb/*.deb
#          credentials: ${{ secrets.credentials }}
#          folder: ${{ secrets.folderId }}

  #      - name: Upload Artifact
  #        uses: actions/upload-artifact@v3
  #        with:
  #          name: linux-binary
  #          path: desktop/build/compose/binaries/main
  #          if-no-files-found: error
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 15
          cache: 'gradle'

      - name: Build
        run: ./gradlew packageDistributionForCurrentOS
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.event.inputs.version, '-rc') || contains(github.event.inputs.version, '-b') || contains(github.event.inputs.version, '-a') }}
          files: |
            desktop\build\**\*.dmg
            desktop\build\**\*.msi
            desktop\build\compose\jars\*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload to Drive
      - name: Upload msi to Google Drive
        uses: anwarpro/upload-to-drive@master
        with:
          target: desktop\build\compose\binaries\main\msi\stockary-1.0.1.msi
          credentials: ${{ secrets.credentials }}
          folder: ${{ secrets.folderId }}